.github/workflows/interop-tests.yml: avoid using dashes in PRE_RELEASE_TAG
rpm complains about double dashes in pkgconfig version:

    error: Invalid version (double separator '-'): 4.1.0-beta2-dev: pkgconfig(libcrypto) = 4.1.0-beta2-dev
    error: Invalid version (double separator '-'): 4.1.0-beta2-dev: pkgconfig(libssl) = 4.1.0-beta2-dev
    error: Invalid version (double separator '-'): 4.1.0-beta2-dev: pkgconfig(openssl) = 4.1.0-beta2-dev

Mangle dashes to tildes in PRE_RELEASE_TAG in VERSION.dat to avoid that.

Signed-off-by: Eugene Syromiatnikov <esyr@openssl.org>
Reviewed-by: Matt Caswell <matt@openssl.foundation>
Reviewed-by: Neil Horman <nhorman@openssl.org>
Reviewed-by: Tomas Mraz <tomas@openssl.foundation>
Merge-date: Tue Oct  6 14:44:07 2026
Merged-from: https://github.com/openssl/openssl/pull/33118
(cherry picked from commit 9d264784fc03cd3ecd41f877f5500cba98e1d104)