Fix to expected bool type in clash compiled void
compiling crash at

/home/eos/libraries/fc/src/crypto/elliptic_r1.cpp:119:14: error: could not convert 'BN_zero_ex(zero)' from 'void' to 'bool'
  119 |         if (!BN_zero(zero)) { ret=-1; goto err; }
      |              ^~~~~~~
      |              |
      |              void

expecting a bool type instead of void, looks like working after updating