Fix unused variable warning/error
The error occurs when using extra warning and error flags with clang:

t_req.c:95:14: error: unused variable 'neg' [-Werror,-Wunused-variable]
        const char *neg;
                    ^
1 error generated.

Signed-off-by: Mike Bland <mbland@acm.org>