Remove redundant header crypto/types.h
Oracle linux build was not compiling due to duplicate typedefs for
ECX_KEY.

crypto/types.h was just a subset of openssl/types.h
ECX_KEY is typedefed in include/crypto/ecx.h

The error was:
In file included from ../include/crypto/evp.h:17,
                 from ../crypto/asn1/a_sign.c:23:
../include/crypto/ecx.h:79: error: redefinition of typedef 'ECX_KEY'
../include/crypto/types.h:22: note: previous declaration of 'ECX_KEY' was here