test/quic_stream_test.c: remove unused tho_heap1024_total global variable
msys-minigw64 workflow with clang compiler started to fail during build
with the following diagnostics:

    test/quic_stream_test.c:3172:53: error: variable 'tho_heap1024_total' set but not used [-Werror,-Wunused-but-set-global]
     3172 | static size_t tho_heap1024_live, tho_heap1024_peak, tho_heap1024_total;
          |                                                     ^

Remove the variable, as it seems that it indeed has no use
in the current version of the test.

Complements: 2d6c7ced4337 "tests: test_dstorage_cleanse() and test_heap_overlap()"
Signed-off-by: Eugene Syromiatnikov <esyr@openssl.org>
Reviewed-by: Milan Broz <mbroz@openssl.org>
Reviewed-by: Neil Horman <nhorman@openssl.org>
Merge-date: Sat Oct 10 16:16:22 2026
Merged-from: https://github.com/openssl/openssl/pull/33180