travis: linux-ppc64le clang - -Wno-pedantic -Wno-missing-prototypes
example warnings:
crypto/ppccap.c:75:6: error: no previous prototype for function
      'sha512_block_data_order' [-Werror,-Wmissing-prototypes]
void sha512_block_data_order(void *ctx, const void *inp, size_t len)

crypto/ppccap.c:113:17: error: assigning to 'void *' from 'void (void *, const
      unsigned char *, size_t, unsigned int)' (aka 'void (void *, const unsigned
      char *, unsigned long, unsigned int)') converts between void pointer and
      function pointer [-Werror,-Wpedantic]
        func[0] = poly1305_blocks_fpu;
                ^ ~~~~~~~~~~~~~~~~~~~

[extended tests]

CLA: trivial