apps/rehash.c: ignore printf format warning [-Wformat]
The `aarch64-linux-android33-clang` cross-compiler (v14.0.6)
complains twice about an unsupported '%n' format specifier,
preventing a successful `--strict-warnings` build:

    error: '%n' specifier not supported on this platform [-Werror,-Wformat]
                BIO_snprintf(buf, buflen, "%s%s%n%08x.%s%d",

This is a false positive, because BIO_snprintf() implements its
own format parsing (which is implemented in the _dopr() function).

To disable the warning, use a GCC pragma instead of a clang pragma,
because the former is recognized by both compilers according to the
[clang manual page][1].

[1]: https://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-via-pragmas