squash! crypto/armcap.c, crypto/ppccap.c: stricter use of getauxval()
Comparing a symbol with NULL gives unnecessary warnings:

    crypto/ppccap.c:278:9: error: comparison of function 'getauxval' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
        if (getauxval != ((void*)0)) {
            ^~~~~~~~~    ~~~~~~~~~~
    crypto/ppccap.c:278:9: note: prefix with the address-of operator to silence this warning
        if (getauxval != ((void*)0)) {
            ^
            &
    1 error generated.

So we fall back to use conditionals to check if getauxval is usable or not