Use trusty for travis builds
this works around build failures due to clang
error: unknown warning option '-Wno-extended-offsetof'

[extended tests]

Reviewed-by: Kurt Roeckx <kurt@roeckx.be>
(Merged from https://github.com/openssl/openssl/pull/9425)